export { default as ArchAwsIq32 } from './ArchAwsIq32'
export { default as ArchAwsManagedServices32 } from './ArchAwsManagedServices32'
export { default as ArchAwsProfessionalServices32 } from './ArchAwsProfessionalServices32'
export { default as ArchAwsSupport32 } from './ArchAwsSupport32'
export { default as ArchAwsTrainingCertification32 } from './ArchAwsTrainingCertification32'