export { default as ResAmazonRekognitionImage48Light } from './ResAmazonRekognitionImage48Light'
export { default as ResAmazonRekognitionVideo48Light } from './ResAmazonRekognitionVideo48Light'
export { default as ResAmazonSagemakerModel48Light } from './ResAmazonSagemakerModel48Light'
export { default as ResAmazonSagemakerNotebook48Light } from './ResAmazonSagemakerNotebook48Light'
export { default as ResAmazonSagemakerTrain48Light } from './ResAmazonSagemakerTrain48Light'