export { default as ArchAwsAmplifyConsole32 } from './ArchAwsAmplifyConsole32'
export { default as ArchAwsAppSync32 } from './ArchAwsAppSync32'
export { default as ArchAwsDeviceFarm32 } from './ArchAwsDeviceFarm32'
export { default as ArchAmazonPinpointJourney32 } from './ArchAmazonPinpointJourney32'
export { default as ArchAmazonPinpoint32 } from './ArchAmazonPinpoint32'